# Generated by Django 6.0.2 on 2026-03-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_ingredients',
            field=models.TextField(blank=True, null=True),
        ),
    ]
